name: "Refresh SSL Cert From Stock Asus DDNS Router"
version: 0.1.0
slug: "refresher_ssl_cert_from_stock_asus_ddns_router"
description: "An Add-on that help refresh the SSL certificate under the /SSL folder from Stock Asus Router DDNS"
startup: once
image: ghcr.io/zulufoxtrot/refresher-ssl-cert-from-stock-asus-ddns-router-{arch}
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - ssl:rw
  - config
environment:
  CONFIG_PATH: /data/options.json
options:
  sslFromAsusRouter:
    routerUser: null
    routerIp: null
    routerSshPort: 22
    rsaPrivateKeyPath: null
    keyFilePathOnRouter: null
    certFilePathOnRouter: null
schema:
  sslFromAsusRouter:
    routerUser: str
    routerIp: str
    routerSshPort: int
    rsaPrivateKeyPath: str
    keyFilePathOnRouter: str
    certFilePathOnRouter: str
