name: release-build
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Release Build
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Get Add-on Release
        uses: KJ002/read-yaml@v1.4
        id: addonVersion
        with:
          file: './config.yaml'
          key-path: '["version"]'

      - name: Display read-yaml output
        run: echo "${{ steps.addonVersion.outputs.data }}"

      - name: Run Release Build
        uses: home-assistant/builder@2024.08.2
        with:
          args: |
            --test \
            --all \
            --target . \
            --image "zulufoxtrot/refresher-ssl-cert-from-stock-asus-ddns-router-amd64" \
            --version 0.1.0 \
            --addon

      - name: Deploy amd64 Release Builds
        run: docker push ghcr.io/zulufoxtrot/refresher-ssl-cert-from-stock-asus-ddns-router-amd64:0.1.0

            
            
            
            
            
